### ISSUE TITLE
[CI] Proposal for Updates to CI

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3650]
CI needs some love, and I have a proposal to make it better. This issue is for discussion of the merits of said proposal: 
 
**Step 1.** 
Reorder existing jobs to be dependent, using tests.py and current templating

```
 jobs:
    - lint
    - update-branch-protection:
        filters:
            branches:
            only: develop
    - tracetool
    - build-wallet
    - build-archive
    - build-macos
    - build-testnet-postake-medium-curves
    - test-foo
        - requires:
            - build-testnet-postake-medium-curves
    - test-bar
        - requires:
            - build-testnet-postake-medium-curves
```

*Benefit:*
This will not drastically speed up the suite as a whole, but it will create a dependency-chain which will allow us to pass artifacts to downstream dependent jobs (which will speed everything up)

**Step 2.** 
Add in [workspace](https://circleci.com/docs/2.0/concepts/#workspaces-and-artifacts) logic, removing builds from testing steps and replacing the binaries with ones built upstream

*Benefit:*
Removes the requirement of building the coda binary during each test, allowing tests to use a binary generated upstream. This will reduce total CI runtime. 

**Step 3.** 
Add in docker image builds
    - Option: use the existing binary that was built in CI via the [workspace](https://circleci.com/docs/2.0/concepts/#workspaces-and-artifacts)
    - Option: use the binary that was published to the Deb repo

*Benefit:*
This will allow us to either quickly build coda docker images, or easily know what `deb` was built so it can be used in the docker build process. 

cc @nholland94 @bkase @jkrauska @cmr
